version: '0.1.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Txt.Core" -c %CONFIGURATION% --no-dependencies --no-restore --version-suffix %LABEL%
- dotnet build "src\Txt.ABNF" -c %CONFIGURATION% --no-dependencies --no-restore --version-suffix %LABEL%
- dotnet build "src\Txt" -c %CONFIGURATION% --no-dependencies --no-restore --version-suffix %LABEL%
- dotnet build "test\Txt.Core.Tests" -c %CONFIGURATION% --no-dependencies --no-restore --version-suffix %LABEL%
- dotnet build "test\Txt.ABNF.Tests" -c %CONFIGURATION% --no-dependencies --no-restore --version-suffix %LABEL%
- dotnet build "sample\Calculator" -c %CONFIGURATION% --no-dependencies --no-restore --version-suffix %LABEL%
after_build:
- dotnet pack "src\Txt.Core" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
- dotnet pack "src\Txt.ABNF" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
- dotnet pack "src\Txt" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
- dotnet publish "sample\Calculator" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
test_script:
- dotnet test "test\Txt.Core.Tests" -c %CONFIGURATION% --no-build
- dotnet test "test\Txt.ABNF.Tests" -c %CONFIGURATION% --no-build
artifacts:
  - path: src\**\*.nupkg
    name: lib
  - path: sample\**\publish
    name: samples
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package
cache:
 - '%USERPROFILE%\.nuget\packages'