version: '2.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:DNX_BUILD_VERSION = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
- dnvm upgrade -r clr
- dnu restore
build:
  parallel: true
test: off
artifacts:
  - path: artifacts\bin\TextFx\**\*.nupkg
  - path: artifacts\bin\TextFx.ABNF\**\*.nupkg
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/textfx/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/textfx/api/v2/package
   on:
     configuration: Debug
 - provider: NuGet
   server: https://www.myget.org/F/textfx/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: true
   on:
     configuration: Release