os: Visual Studio 2015
version: '2.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:PRERELEASE = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
- ps: dnvm upgrade -u -r clr
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe' -FileName 'dotnetcli.exe'
- ps: .\dotnetcli.exe /quiet
- ps: $Env:PATH += ';%PROGRAMFILES%\dotnet\'
- ps: dotnet restore
build_script:
- dotnet pack -o artifacts\. -c $Env:CONFIGURATION --version-suffix $Env:PRERELEASE .\src\Txt\
- dotnet pack -o artifacts\. -c $Env:CONFIGURATION --version-suffix $Env:PRERELEASE .\src\Txt.ABNF\
test: off
artifacts:
  - path: artifacts\*.nupkg
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package