version: '2.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
build_script:
- appveyor-retry dotnet restore -v Minimal
- dotnet build "src\Common" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Txt.Core" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet pack "src\Txt.Core" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet build "src\Txt.ABNF" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet pack "src\Txt.ABNF" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet build "src\Txt" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet pack "src\Txt" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet test "test\Txt.Core.Tests"
- dotnet test "test\Txt.ABNF.Tests"
artifacts:
  - path: artifacts\**\*.*
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package
cache:
 - '%USERPROFILE%\.nuget\packages'