os: Visual Studio 2015
version: '2.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:DNX_BUILD_VERSION = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
- dnvm upgrade -u -r clr
- choco install dotnetcli
- set PATH=%PATH%;%PROGRAMFILES%\dotnet\
- dotnet restore
build:
  parallel: true
test: off
artifacts:
  - path: artifacts\bin\Txt\**\*.nupkg
  - path: artifacts\bin\Txt.ABNF\**\*.nupkg
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package