os: Visual Studio 2015
version: '2.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:PRERELEASE = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001598/dotnet-win-x64.1.0.0.001598.exe' -FileName 'dotnetcli.exe'
- cmd: dotnetcli.exe /quiet
- cmd: PATH = %PATH%;%PROGRAMFILES%\dotnet\bin\
- cmd: dnvm upgrade -u -r clr
build_script:
- appveyor-retry nuget restore
- ps: ls -Recurse project.json | %{ dotnet build $_ -c $Env:CONFIGURATION --version-suffix $Env:PRERELEASE }
- dotnet pack --no-build -o artifacts\. .\src\Txt.Core\
- dotnet pack --no-build -o artifacts\. .\src\Txt.ABNF\
- dotnet pack --no-build -o artifacts\. .\src\Txt\
test: off
artifacts:
  - path: artifacts\*.nupkg
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package
cache:
 - '%USERPROFILE%\.nuget\packages'