os: Visual Studio 2015
version: '2.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
init:
 - ps: $Env:PRERELEASE = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- dotnet-dev-win-x64.latest.exe /quiet
- dnvm upgrade -u -r clr
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
build_script:
- appveyor-retry dotnet restore -v Minimal
- dotnet build **\project.json -c %CONFIGURATION%
- dotnet pack --no-build --version-suffix %PRERELEASE% -o artifacts\. .\src\Txt.Core\
- dotnet pack --no-build --version-suffix %PRERELEASE% -o artifacts\. .\src\Txt.ABNF\
- dotnet pack --no-build --version-suffix %PRERELEASE% -o artifacts\. .\src\Txt.UTF8\
- dotnet pack --no-build --version-suffix %PRERELEASE% -o artifacts\. .\src\Txt\
test: off
artifacts:
  - path: artifacts\*.nupkg
deploy:
 - provider: NuGet
   server: https://www.myget.org/F/ci/api/v2/package
   api_key:
     secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
   skip_symbols: false
   symbol_server: https://www.myget.org/F/ci/api/v2/package
cache:
 - '%USERPROFILE%\.nuget\packages'