version: '{build}'
configuration:
- Debug
- Release
platform: Any CPU
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 2.0
  assembly_file_version: 2.0.{build}
  assembly_informational_version: 2.0.0-CI{build}0
before_build:
- cmd: nuget restore
build:
  project: TextFx.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: detailed
deploy:
- provider: NuGet
  server: https://www.myget.org/F/textfx/api/v2/package
  api_key:
    secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
  skip_symbols: false
  symbol_server: https://nuget.symbolsource.org/MyGet/textfx
  on:
    configuration: Debug
- provider: NuGet
  server: https://www.myget.org/F/textfx/api/v2/package
  api_key:
    secure: Qwf1a1BP2lCg6c9F5xt7hwDVciba1FhiYewLIAGzAVLeNh0TiAamxz78W06ij4tp
  skip_symbols: true
  on:
    configuration: Release